comment:
  require_changes: true
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto 
        flags: 
          - unittests
        if_ci_failed: error
