name: build
on:
  create: {}
  push:
    paths-ignore:
      - '*.md'
      - '**/*.md'
    branches:
      - master
  pull_request:
    paths-ignore:
      - '*.md'
      - '**/*.md'
    types:
      - opened
      - edited
      - synchronize

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: openjdk:8
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: ./gradlew build --info