name: build
on: 
  push:
    paths-ignore:
      - '*.md'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '*.md'
      - '**/*.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: openjdk:8
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: ./gradlew build --info