name: ci
on:
  create: {}
  push:
    paths-ignore:
      - '*.md'
      - '**/*.md'
    branches:
      - master
      - release/**
  pull_request:
    paths-ignore:
      - '*.md'
      - '**/*.md'
    types:
      - opened
      - edited
      - synchronize

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: openjdk:8
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: ./gradlew build --info

      - name: Release
        env:
          GITHUB_PKG_USERNAME: javatmc
          GITHUB_PKG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish
    